spring.application.name=nba-non-betting-app
# This is just for disabling the database part for now
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-nameless-sound-ai0wa5s7-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_Password}


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# balldontlie API
balldontlie.base-url=https://api.balldontlie.io/nba/v1
balldontlie.api-key=${BDL_API_KEY}
